name: Build and Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build devcontainer
        run: docker build .devcontainer -t devcontainer
      - name: Build pihole-influx-exporter
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
            -w /workspace devcontainer \
            bash -c "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build"
      - name: Build Docker image
        run: docker build . -t jacogasp/pihole-influx-exporter
